apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-infra-apps
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
 # finalizers:
 #   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/stromberg2/argocd.git
    targetRevision: HEAD
    path: k8s-infra-apps
    directory:
     recurse: true
     jsonnet: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: k8s-infra
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true  